version: "3.9"

services:
  postgres:
    image: postgres:10.7-alpine
    environment:
      - POSTGRES_PASSWORD=scheduleDB
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"